# Generated by Django 3.2.7 on 2021-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/static/images/jeremy-perkins-UgNjyPkphtU-unsplash.jpg', upload_to='profile_pictures/'),
        ),
    ]
