# Generated by Django 3.2.7 on 2021-09-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_remove_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myprojects', to='review_app.projects'),
        ),
    ]
