# Generated by Django 3.2.7 on 2021-09-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0008_auto_20210917_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='myprojects', to='review_app.projects'),
        ),
    ]
