# Generated by Django 3.2.7 on 2021-09-17 12:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0009_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
